model_params:
  model_name: 'transformer'
  hidden_size: [32] #[32, 64, 128]
  num_layers: [2] #[1, 2, 3]
  dropout: [0.1] #[0., 0.1]
  num_heads: [4]
  classification_token: ['first', 'last', 'all']

exp_params:
  train_valid_ratio: 0.8
  label_constraints: [True] #[ True, False ]


  test_flag: False
  last_version: 23

  # DNNs
  batch_size: [25] #[50, 100, 150]
  learning_rate: [0.01] #[0.1, 0.01, 0.001]
  num_workers: 0
  normalization: ['none', 'minmax', 'standard'] #['none', 'minmax', 'standard']

  target_name: ['fault', 'location', 'starttime']
  data_path: '../processed_datasets/dataset_V1.pkl'

trainer_params:
  max_epochs: 2 #NOTE: by default, it is 50
  gpus: [1]

logging_params:
  save_dir: './../logs'
  name: 'transformer'
  manual_seed: 0