model_params:
  model_name: 'arima'

exp_params:
  variate: ['uni'] #['uni', 'multi']
  sliding_window: [120]
  p_values: [2] #[1, 2, 4, 6, 8, 10]
  d_values: [2] #[1, 2]
  q_values: [2] #[1, 2]
  selection_metric: 'RMSE' # one of ['RMSE', 'MAE', 'MAPE']

  train_valid_ratio: 0.99

  external_feature_flag: [False] #[False, True]
  external_features: ['month_day', 'weekday', 'holiday', 'DHI', 'DNI', 'GHI', 'Dew Point', 'Solar Zenith Angle', 'Wind Speed', 'Relative Humidity', 'Temperature']

  test_flag: False
  last_version: 25

  prediction_interval: 0.95

  data_folder: '/meladyfs/newyork/nanx/freetime/freetime/PowerSystem/processed_datasets/forecasting'

trainer_params:


logging_params:
  save_dir: './../logs'
  name: 'arima'
  manual_seed: 0