model_params:
  model_name: 'exponential_smoothing'

exp_params:
  sliding_window: [ 1440 ]
#  ep_method: 'simple' # in ['simple', 'Holt', 'Holt Winters']
  selection_metric: 'RMSE' # one of ['RMSE', 'MAE', 'MAPE']

  train_valid_ratio: 0.99

  test_flag: False
  last_version: 2

  prediction_interval: 0.95

  data_folder: '/meladyfs/newyork/nanx/freetime/freetime/PowerSystem/processed_datasets/forecasting'

trainer_params:


logging_params:
  save_dir: './../logs'
  name: 'exponential_smoothing'
  manual_seed: 0