model_params:
  model_name: 'LSTNet'
  dropout: [0.2] #[0., 0.1]
  hidRNN: [100]
  hidCNN: [100]
  hidSkip: [10]
  cnn_kernel: [6]
  skip: [24]
  highway_window: [24]

exp_params:

  sliding_window: [ 120 ]
  selection_metric: 'RMSE' # one of ['RMSE', 'MAE', 'MAPE']

  train_valid_ratio: 0.9

  external_features: ['month_day', 'weekday', 'holiday', 'DHI', 'DNI', 'GHI', 'Dew Point', 'Solar Zenith Angle', 'Wind Speed', 'Relative Humidity', 'Temperature']

  test_flag: False
  last_version: 23

  # DNNs
  batch_size: [128] #[50, 100, 150]
  learning_rate: [0.001] #[0.1, 0.01, 0.001]
  num_workers: 0
  normalization: ['minmax'] #['none', 'minmax', 'standard']

  prediction_interval: 0.95

  data_folder: '/meladyfs/newyork/nanx/freetime/freetime/PowerSystem/processed_datasets/forecasting'

trainer_params:
  max_epochs: 2 #NOTE: by default it's 50
  gpus: [2]

logging_params:
  save_dir: './../logs'
  name: 'LSTNet'
  manual_seed: 0